// Generated by gencpp from file ugv_ros/GoToGoal.msg
// DO NOT EDIT!


#ifndef UGV_ROS_MESSAGE_GOTOGOAL_H
#define UGV_ROS_MESSAGE_GOTOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ugv_ros
{
template <class ContainerAllocator>
struct GoToGoal_
{
  typedef GoToGoal_<ContainerAllocator> Type;

  GoToGoal_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  GoToGoal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::ugv_ros::GoToGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ugv_ros::GoToGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GoToGoal_

typedef ::ugv_ros::GoToGoal_<std::allocator<void> > GoToGoal;

typedef boost::shared_ptr< ::ugv_ros::GoToGoal > GoToGoalPtr;
typedef boost::shared_ptr< ::ugv_ros::GoToGoal const> GoToGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ugv_ros::GoToGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ugv_ros::GoToGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ugv_ros::GoToGoal_<ContainerAllocator1> & lhs, const ::ugv_ros::GoToGoal_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ugv_ros::GoToGoal_<ContainerAllocator1> & lhs, const ::ugv_ros::GoToGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ugv_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ugv_ros::GoToGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ugv_ros::GoToGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ugv_ros::GoToGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ugv_ros::GoToGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ugv_ros::GoToGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ugv_ros::GoToGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ugv_ros::GoToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71344c0ba01936756dc45bcd89ef437";
  }

  static const char* value(const ::ugv_ros::GoToGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71344c0ba019367ULL;
  static const uint64_t static_value2 = 0x56dc45bcd89ef437ULL;
};

template<class ContainerAllocator>
struct DataType< ::ugv_ros::GoToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ugv_ros/GoToGoal";
  }

  static const char* value(const ::ugv_ros::GoToGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ugv_ros::GoToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"float64 x\n"
"float64 y\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::ugv_ros::GoToGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ugv_ros::GoToGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ugv_ros::GoToGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ugv_ros::GoToGoal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UGV_ROS_MESSAGE_GOTOGOAL_H
