// Generated by gencpp from file ugv_ros/GoToResult.msg
// DO NOT EDIT!


#ifndef UGV_ROS_MESSAGE_GOTORESULT_H
#define UGV_ROS_MESSAGE_GOTORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ugv_ros
{
template <class ContainerAllocator>
struct GoToResult_
{
  typedef GoToResult_<ContainerAllocator> Type;

  GoToResult_()
    : result()  {
    }
  GoToResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ugv_ros::GoToResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ugv_ros::GoToResult_<ContainerAllocator> const> ConstPtr;

}; // struct GoToResult_

typedef ::ugv_ros::GoToResult_<std::allocator<void> > GoToResult;

typedef boost::shared_ptr< ::ugv_ros::GoToResult > GoToResultPtr;
typedef boost::shared_ptr< ::ugv_ros::GoToResult const> GoToResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ugv_ros::GoToResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ugv_ros::GoToResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ugv_ros::GoToResult_<ContainerAllocator1> & lhs, const ::ugv_ros::GoToResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ugv_ros::GoToResult_<ContainerAllocator1> & lhs, const ::ugv_ros::GoToResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ugv_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ugv_ros::GoToResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ugv_ros::GoToResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ugv_ros::GoToResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ugv_ros::GoToResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ugv_ros::GoToResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ugv_ros::GoToResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ugv_ros::GoToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::ugv_ros::GoToResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::ugv_ros::GoToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ugv_ros/GoToResult";
  }

  static const char* value(const ::ugv_ros::GoToResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ugv_ros::GoToResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string result\n"
;
  }

  static const char* value(const ::ugv_ros::GoToResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ugv_ros::GoToResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ugv_ros::GoToResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ugv_ros::GoToResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UGV_ROS_MESSAGE_GOTORESULT_H
