// Generated by gencpp from file ugv_ros/GoTo.msg
// DO NOT EDIT!


#ifndef UGV_ROS_MESSAGE_GOTO_H
#define UGV_ROS_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <ugv_ros/GoToRequest.h>
#include <ugv_ros/GoToResponse.h>


namespace ugv_ros
{

struct GoTo
{

typedef GoToRequest Request;
typedef GoToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoTo
} // namespace ugv_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ugv_ros::GoTo > {
  static const char* value()
  {
    return "6535ac972b19122cf7fc9c3a775320c8";
  }

  static const char* value(const ::ugv_ros::GoTo&) { return value(); }
};

template<>
struct DataType< ::ugv_ros::GoTo > {
  static const char* value()
  {
    return "ugv_ros/GoTo";
  }

  static const char* value(const ::ugv_ros::GoTo&) { return value(); }
};


// service_traits::MD5Sum< ::ugv_ros::GoToRequest> should match
// service_traits::MD5Sum< ::ugv_ros::GoTo >
template<>
struct MD5Sum< ::ugv_ros::GoToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ugv_ros::GoTo >::value();
  }
  static const char* value(const ::ugv_ros::GoToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ugv_ros::GoToRequest> should match
// service_traits::DataType< ::ugv_ros::GoTo >
template<>
struct DataType< ::ugv_ros::GoToRequest>
{
  static const char* value()
  {
    return DataType< ::ugv_ros::GoTo >::value();
  }
  static const char* value(const ::ugv_ros::GoToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ugv_ros::GoToResponse> should match
// service_traits::MD5Sum< ::ugv_ros::GoTo >
template<>
struct MD5Sum< ::ugv_ros::GoToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ugv_ros::GoTo >::value();
  }
  static const char* value(const ::ugv_ros::GoToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ugv_ros::GoToResponse> should match
// service_traits::DataType< ::ugv_ros::GoTo >
template<>
struct DataType< ::ugv_ros::GoToResponse>
{
  static const char* value()
  {
    return DataType< ::ugv_ros::GoTo >::value();
  }
  static const char* value(const ::ugv_ros::GoToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UGV_ROS_MESSAGE_GOTO_H
