// Generated by gencpp from file ugv_ros/GoToFeedback.msg
// DO NOT EDIT!


#ifndef UGV_ROS_MESSAGE_GOTOFEEDBACK_H
#define UGV_ROS_MESSAGE_GOTOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ugv_ros
{
template <class ContainerAllocator>
struct GoToFeedback_
{
  typedef GoToFeedback_<ContainerAllocator> Type;

  GoToFeedback_()
    : x()
    , y()
    , yaw()  {
    }
  GoToFeedback_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , yaw(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::ugv_ros::GoToFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ugv_ros::GoToFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GoToFeedback_

typedef ::ugv_ros::GoToFeedback_<std::allocator<void> > GoToFeedback;

typedef boost::shared_ptr< ::ugv_ros::GoToFeedback > GoToFeedbackPtr;
typedef boost::shared_ptr< ::ugv_ros::GoToFeedback const> GoToFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ugv_ros::GoToFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ugv_ros::GoToFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ugv_ros::GoToFeedback_<ContainerAllocator1> & lhs, const ::ugv_ros::GoToFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ugv_ros::GoToFeedback_<ContainerAllocator1> & lhs, const ::ugv_ros::GoToFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ugv_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ugv_ros::GoToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ugv_ros::GoToFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ugv_ros::GoToFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dc50e8eb6421d2ce141adb59591391a";
  }

  static const char* value(const ::ugv_ros::GoToFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dc50e8eb6421d2cULL;
  static const uint64_t static_value2 = 0xe141adb59591391aULL;
};

template<class ContainerAllocator>
struct DataType< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ugv_ros/GoToFeedback";
  }

  static const char* value(const ::ugv_ros::GoToFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64[] x\n"
"float64[] y\n"
"float64[] yaw\n"
"\n"
;
  }

  static const char* value(const ::ugv_ros::GoToFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ugv_ros::GoToFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ugv_ros::GoToFeedback_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "yaw[]" << std::endl;
    for (size_t i = 0; i < v.yaw.size(); ++i)
    {
      s << indent << "  yaw[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.yaw[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UGV_ROS_MESSAGE_GOTOFEEDBACK_H
